safe-global/safe-smart-account

- contracts/GnosisSafe.sol
- contracts/GnosisSafePersonalEdition.sol
- contracts/GnosisSafeTeamEdition.sol
- package-lock.json
- package.json
- test/gnosisSafePersonalEditionEthSignTypeData.js
- test/utilsPersonalSafe.js
- truffle.js
Implements #43: Use EIP-712 for hashing
Uses EIP-712 for hashing. This will allow other key stores to sign safe transactions (e.g. MetaMask, Ledger, Trezor). 
This introduces additional gas costs of ~20k on creation and ~700 per transaction.
> Implements #43: Use EIP-712 for hashing

- package-lock.json
- package.json
- test/dailyLimitModule.js
- test/gnosisSafePersonalEdition.js
- test/gnosisSafePersonalEditionCreation.js
New API has breaking changes but makes interaction much simpler. No more need for cumbersome abi.encoding in JS.
Ran truffle test to verify everything still works.
> Upgrade MockContract to version 2.0

- .gitignore
- contracts/GnosisSafe.sol
- contracts/base/ModuleManager.sol
- contracts/base/OwnerManager.sol
- contracts/interfaces/ISignatureValidator.sol
- test/gnosisSafePersonalEditionManagers.js
If a user theoretically manages to deploy a contract to address 0x01 it would be possible to exploit an edge case to gain access to the Safe.
This is in practice not possible, as it is impossible to deploy to a specific address (also 0x01 is reserved for a precomile)
> Added sentinel tests

- README.md
- contracts/GnosisSafe.sol
- contracts/common/SignatureDecoder.sol
- contracts/interfaces/ISignatureValidator.sol
- package-lock.json
- package.json
- test/createAndAddModules.js
- test/dailyLimitModule.js
- test/gnosisSafePersonalEdition.js
- test/gnosisSafePersonalEditionCreation.js
- test/gnosisSafePersonalEditionEthSignTypeData.js
- test/gnosisSafePersonalEditionManagers.js
- test/gnosisSafePersonalEditionNestedSafes.js
- test/gnosisSafePersonalEditionSignatureValidatorErrors.js
- test/gnosisSafeTeamEdition.js
- test/multiSend.js
- test/safeMethodNaming.js
- test/socialRecoveryModule.js
- test/stateChannelModule.js
- test/utils/execution.js
- test/utils/general.js
- test/whitelistModule.js
- Implemented critical proposals from https://github.com/runtimeverification/verified-smart-contracts/blob/master/gnosis/GnosisSafe_RuntimeVerification.pdf
- Adjusted EIP-1271 interface
- Cleanup of naming
> Fixes for 1.0.0

- README.md
Expands the ZeppelinOS section in the README instructing an end user how to link to this EVM package and use it from their project. Note that this will only work after the npm package is published.
> Expand README explaining how to use as an EVM package

- contracts/GnosisSafe.sol
- test/gnosisSafeTransactionExecution.js
- test/utils/execution.js
- If gasToken is ETH and gasprice is higher than tx.gasprice then tx.gasprice will be used to calculate the gas fee refund
- If gasToken is NOT ETH then nothing will change
> Use tx.gasprice if lower than signed gasprice for ETH

- contracts/GnosisSafe.sol
- test/gnosisSafeEthSign.js
I added this, since it would allow us to support all existing wallets. While EIP-712 based signatures are still the preferred way, this would enable also wallets that do not support this EIP to generate signatures.
This also does not break backwards compatibility. And theoretically could be removed again in the future.
> Add eth_sign support

- contracts/GnosisSafe.sol
- contracts/base/FallbackManager.sol
- contracts/base/ModuleManager.sol
- test/createCall.js
- test/gnosisSafeDeploymentViaCreate2.js
- test/gnosisSafeDeploymentViaTx.js
- test/gnosisSafeManagement.js
- test/gnosisSafeSignatureTypes.js
- test/gnosisSafeTransactionExecution.js
- test/multiSend.js
- test/utils/execution.js
Closes #133
This PR adds events for all kinds of interactions with the Safe. This will make it easier for 3rd party clients to monitor Safe instances. 
The additional costs are between 2% when executing a transaction. For incoming transactions there is an additional 1k required.
Current event definitions (for a better overview):
```js
event ApproveHash(
bytes32 indexed approvedHash,
address indexed owner
);
event SignMsg(
bytes32 indexed msgHash
);
event ExecutionFailure(
bytes32 txHash, uint256 payment
);
event ExecutionSuccess(
bytes32 txHash, uint256 payment
);
event ExecutionFromModuleSuccess(
address indexed module
);
event ExecutionFromModuleFailure(
address indexed module
);
event IncomingTransaction(
address from, uint256 value
);
```
> Closes #133: Added events + required refactoring

- contracts/proxies/Proxy.sol
- test/gnosisSafeDeploymentViaCreate2.js
Closes #130 
This PR adds a way to pull the master copy of a proxy on chain.
The costs on deployment increase by 10k gas because of this change (~ 5%), but there is close to no change in the execution costs per transaction.
> Close #130: Add method to access master copy

- contracts/GnosisSafe.sol
- contracts/base/FallbackManager.sol
- contracts/base/ModuleManager.sol
- contracts/base/OwnerManager.sol
- contracts/common/MasterCopy.sol
- contracts/proxies/Proxy.sol
- package-lock.json
- package.json
- test/gnosisSafeForceSafeSetup.js
- test/gnosisSafeIncomingSend.js
See #149 
- Only emit the event for incoming transactions in the mastercopy in case of an EOA transfer or if enough gas is available
- Note: we do NOT emit an event in the Proxy to avoid changes in behavior in different Safe versions and let the master copy handle every call
- Make constants private to minimize code (required to avoid issues with EIP-170)
- Optimize getModules to avoid issues with EIP-170
> Closes #149: Attempt to fix send/ transfer issue

- contracts/base/FallbackManager.sol
As a result of the audit it was recommended to remove this event, because it is not dependable in the current implementation and might break with future gas changes.
@Georgi87 @Uxio0 what do you think?
> Remove incoming transaction event

- contracts/libraries/MultiSend.sol
- test/multiSend.js
- Enforce that the multi send contract can only be called via a delegate call
> Update multi send

- contracts/GnosisSafe.sol
- migrations/4_deploy_master_copies.js
- scripts/deploy_safe_contracts_oz.js
- scripts/init_contracts.js
- test/createAndAddModules.js
- test/createCall.js
- test/dailyLimitModule.js
- test/defaultCallbackHandler.js
- test/gnosisSafe0xExploit.js
- test/gnosisSafeDeploymentViaCreate2.js
- test/gnosisSafeDeploymentViaTx.js
- test/gnosisSafeEthSign.js
- test/gnosisSafeEthSignTypeData.js
- test/gnosisSafeExecuteFromModule.js
- test/gnosisSafeForceSafeSetup.js
- test/gnosisSafeIncomingSend.js
- test/gnosisSafeManagement.js
- test/gnosisSafeMasterCopyDeployment.js
- test/gnosisSafeNestedSafes.js
- test/gnosisSafeSignatureTypes.js
- test/gnosisSafeSignatureValidatorErrors.js
- test/gnosisSafeTransactionExecution.js
- test/multiSend.js
- test/socialRecoveryModule.js
- test/stateChannelModule.js
- test/whitelistModule.js
Added a constructor that will render the Safe contract unusable by anyone, so that it can be ensured that the mastercopy cannot be manipulated.
This should improve the security of the deployed mastercopy (see deployment notes in the audit report)
> Add master copy constructor

- contracts/GnosisSafe.sol
- test/gnosisSafeTransactionExecution.js
- test/utils/execution.js
Closes #186: Make execTransaction payable
- Allows to send ETH along to Safe executing tx
> Closes #186: Make execTransaction payable

- README.md
The readme wrongly mentioned that Alexey audited version 0.2.0 (this version doesn't exist) ... the correct version is 0.0.1. All other information regarding this audit are correct (e.g. referenced commit)
> Update audit description

- contracts/base/OwnerManager.sol
- test/core/GnosisSafe.OwnerManager.spec.ts
- test/core/GnosisSafe.Setup.spec.ts
Closes #229 
Add checks to disallow Safe as owner of itself with default methods
#229 proposes to prevent adding the Safe as an owner of itself and to check on execution if the signer is the Safe itself.
For this PR checks have been added to:
- `setup`
- `addOwnerWithThreshold`
- `swapOwner`
No check has been added to the execution process, as this would prevent user from potentially recovering a Safe that has itself as an owner. To get into this state after this update you would need to use a delegate call that messes with the Safes state. This is out of scope of our checks (as we expect users to pay special attention to delegate calls)
> Closes #229: Safe can be added as owner of itself

- contracts/base/OwnerManager.sol
- test/core/GnosisSafe.OwnerManager.spec.ts
- test/core/GnosisSafe.Setup.spec.ts
Closes #244 
- Adds check to setup that includes the duplication check on the `currentOwner` that has not yet been persisted
> Closes #244: Prevent duplicate owners on setup

- contracts/common/EtherPaymentFallback.sol
- test/core/GnosisSafe.Execution.spec.ts
- test/core/GnosisSafe.Incoming.spec.ts
Closes #209
- Added `SafeReceived` event
- Change `send` and `transfer` test to expect revert
Note: This PR is based on #277
> Closes #209: Add event for incoming eth

- benchmark/GnosisSafe.Creation.spec.ts
- benchmark/utils/setup.ts
- contracts/GnosisSafe.sol
- test/core/GnosisSafe.Execution.spec.ts
- test/core/GnosisSafe.Setup.spec.ts
- test/utils/execution.ts
- test/utils/setup.ts
> Closes #233: Add setup event

- contracts/GnosisSafe.sol
- contracts/handler/HandlerContext.sol
Closes #246 
- Add warning for `_msgSender` to make it clear that only is supported with the correct manager
- Adjusted version string in contract to `1.3.0`
> Closes #246: Add warning for _msgSender

- contracts/handler/DefaultCallbackHandler.sol
- contracts/interfaces/IERC165.sol
- test/handlers/DefaultCallbackHandler.spec.ts
Closes #161
- Add EIP-165 handling for ERC-721
- Add EIP-165 handling for ERC-1155
> Closes #161: Add EIP-165 support in DefaultCallbackHandler

- contracts/common/StorageAccessible.sol
- contracts/handler/CompatibilityFallbackHandler.sol
- test/core/GnosisSafe.StorageAccessible.spec.ts
Veondor code from latest version of StorageAcccessible (see https://github.com/gnosis/util-contracts/blob/solc-7/contracts/StorageAccessible.sol)
It is expected that the same is used by GPv2 therefore the interface is kept the same so it will be possible to share related tool/ code.
> Update StorageAccessible implementation

- contracts/GnosisSafe.sol
- contracts/GnosisSafeL2.sol
- contracts/base/FallbackManager.sol
- contracts/base/OwnerManager.sol
- contracts/common/SecuredTokenTransfer.sol
- contracts/common/StorageAccessible.sol
- contracts/guards/DelegateCallTransactionGuard.sol
- contracts/handler/CompatibilityFallbackHandler.sol
- contracts/handler/HandlerContext.sol
Applied recommendations:
- Change `CompatibilityFallbackHandler.simulate` to `external` to enforce correct calldata layout
- In `SecuredTokenTransfer` the boolean return value of the call could be directly written to scratch space by the call function instead of using returndatacopy to retrieve it
Unapplied recommendations:
- Use hash instead of whole message to call `signMessage`
- This change will not be applied, as the current method should be kept for backwards compatibility and the new message could be added via a lib. In any case the chances are high that this method is removed in the future.
- Remove unused return value from `GnosisSafeProxyFactory.calculateCreateProxyWithNonceAddress`
- This will be kept as an indicator what we encode into the revert message.
Additional changes:
- …
> Implement audit notes

- contracts/accessors/SimulateTxAccessor.sol
- contracts/libraries/Migrate_1_3_0_to_1_2_0.sol
- contracts/libraries/MultiSend.sol
- test/migration/subTests.spec.ts
Replace guards with immutable that can be used to check against `this` at runtime
> Optimize delegatecall check

- contracts/GnosisSafe.sol
- contracts/libraries/Migrate_1_3_0_to_1_2_0.sol
- test/core/GnosisSafe.Signatures.spec.ts
Adds `checkNSignatures` that allows to specify the number of expected signatures. This will allow external contracts (e.g. modules, guard or fallback handlers) to easily check signatures against the safe owners without having to rely on the threshold.
Examples:
- A transaction guard could check against all owners for specific transactions
- A EIP-1271 fallback handler could require less signatures for specific signatures.
> Add checkNSignatures method

- CHANGELOG.md
- README.md
This should warn the developers that they should use the tagged versions to get the audited code
> Add dev warning to readme

- test/libraries/SignMessageLib.spec.ts
threshold/owner count slots were confused in signmessagelib tests
> naming correction in `SignMessageLib` tests

- hardhat.config.ts
I had to add these networks to redeploy the 1.3.0 SignMessageLib contract
> add avalanche config

- contracts/handler/CompatibilityFallbackHandler.sol
The reason behind the PR has already been explained well by @chriseth in a similar PR to OpenZeppelin (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3293) so I'll copy that description here:
> First, I would like to apologize. Somehow the issue [ethereum/solidity#10900](https://github.com/ethereum/solidity/issues/10900) got lost in our backlog. We are currently fixing it and discovered one instance of this in openzeppelin. This PR fixes it.
> 
> More details:
> 
> The function `hashProposal` in the interface is declared with `calldata` parameters while its implementation in Governor uses `memory`. This leads to invalid code being generated whenever someone calls the `hashProposal` function internally on the interface instead of the implementation. This can only happen if you …
> Align data location of interface with implementation

- test/libraries/Migration.spec.ts
Hardhat 2.9.5 released yesterday introduced a requirement for storage addresses passed to `getStorageAt()` to be padded to full 32 bytes. Currently the Safe has one test that uses an unpadded argument and that test is failing with latest Hardhat.
This PR adds the missing padding. Note that Hardhat has a bug that makes it still reject the properly padded address (https://github.com/NomicFoundation/hardhat/issues/2709) but once that's fixed, this change will be enough to solve the issue.
```bash
hardhat test test/libraries/Migration.spec.ts
```
```
Migration
constructor
✓ can not use 0 Address
migrate
✓ can only be called from Safe itself
1) can migrate
2 passing (3s)
1 failing
1) Migration
migrate
can migrate:
InvalidArgumentsError: Errors encountered in param 1: Storage slot argument must …
```
> Pad storage addresses passed to `getStorageAt()` to 66 chars

- contracts/base/FallbackManager.sol
- docs/error_codes.md
- test/core/Safe.FallbackManager.spec.ts
- test/core/Safe.Setup.spec.ts
This PR:
- Adds a check that the FallbackHandler address is not equal to the safe. Otherwise, it may open some attack vector if the safe had a protected method with 0 parameters due to the `msg.sender` address appendix
> Check that fallback handler address is not equal to self

- contracts/handler/CompatibilityFallbackHandler.sol
Https://github.com/safe-global/safe-contracts/pull/547 initially fixed it.
It fixes an incorrect documentation for the EIP-1271 method return value
> Docs: Fix return value comment

- .github/workflows/cla.yml
Github will stop supporting NodeJS 12 (used by the current version) and this new version uses NodeJS 16
> Update CLA github action to v2.3.0

- CHANGELOG.md
In the changelog the addresses mentioned were still for 1.4.0.
> Fix addresses for 1.4.1 in changelog

- contracts/Safe.sol
- contracts/handler/CompatibilityFallbackHandler.sol
- contracts/interfaces/ISignatureValidator.sol
- docs/error_codes.md
- test/core/Safe.Signatures.spec.ts
- test/handlers/CompatibilityFallbackHandler.spec.ts
- test/integration/Safe.0xExploit.spec.ts
**Context:**
Safe contract supports contract signature validation using EIP-1271. The Safe contracts defines [an interface](https://github.com/safe-global/safe-contracts/blob/main/contracts/interfaces/ISignatureValidator.sol) which has a function declaration `isValidSignature(bytes, bytes)` which is used to validating the contract signatures. But, [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) defines `isValidSignature(bytes32,bytes)` for validating contract signatures. This PR addresses this issue by removing the use of legacy implementation of EIP-1271.
Fixes: https://github.com/safe-global/safe-contracts/issues/391
Forum discussion: https://forum.safe.global/t/safe-contract-v1-5-0/3383
**Motivation**
- By complying to updated EIP-1271 standard will allow safe contracts to interact …
> Support updated EIP-1271 implementation for signature validation

- docs/safe_tx_gas.md
Hey :wave:,
This PR will fix :
1 typo in `docs/safe_tx_gas.md`
Best!
> docs: fix typos

- certora/configs/Owner.conf
- certora/specs/OwnerReach.spec
As discussed earlier, here is the specification that uses a ghost predicate reach to express whether elements are transitively reachable from another via the owners linked list.  This should help to prove that every owner is on the linked list.
This is only tested on staging with the beta version.  To run this, install certora-cli-beta and run
```
certoraRun certora/configs/Owner.conf --server staging
```
The spec is still not completely passing.  Especially the initialization seems to be problematic for some of the invariants.
Also the setup function may corrupt the list, so one has to prove that it can never called e.g. by stating an invariant that threshold is never zero.
> Specification proving reachability for all elements

- certora/specs/OwnerReach.spec
This fixes one of the failing invariants by proving that setup() is not callable because threshold is always set.
> fix inListReachable_preserve for setup

- certora/configs/Owner.conf
- certora/specs/OwnerReach.spec
This fixes some problems with the previous invariants.
The main part is adding new rules that verify that `isOwner`, `addOwnerWithThreshold`, `removeOwner` and `swapOwner` behave as intended.
In particular it checks that
- getThreshold() is always between 1 and ownerCount.
- isOwner returns false for SENTINEL and current contract.
- isOwner's result agrees with ghostOwners.
- addOwner adds an owner and doesn't change other owners.
- removeOwner removes an owner and doesn't change other owners.
- swapOwner removes old owner, adds new owner, and doesn't change other owners.
> Formal Verification: Rules for is/add/remove/swapOwner

- .env.sample
- .github/workflows/ci.yml
- .solcover.js
This PR:
- Skips test files that were introduced during work on 1.4.1 and 1.5.0 and negatively affected test coverage
- Includes the environment variable used for Safe Contract instance under testing to the sample env file
- Use SafeL2 contract for the coverage test
> Chore: skip test files in coverage, use SafeL2 contract for coverage calculation

- certora/conf/signatures.conf
The checkSignatures verification timed out on the CI on main. I looked into it, and the reason could be the options we pass to the prover. I restored the options from the [original PR](https://github.com/safe-global/safe-contracts/pull/661) from Jochen in an attempt to fix this.
Fixes #681
> Feature: Signatures rule fix by restoring the prover options from the original PR

- .github/workflows/ci.yml
- .husky/pre-commit
- package.json
- Check linting and formatting of Typescript and Solidity files
- Split linting and formatting checking on Github Actions
- Refactor `NODE_VERSION` on Github Actions into an environment variable
> Add pre-commit hook for linting and formatting

- contracts/libraries/MultiSend.sol
- contracts/libraries/MultiSendCallOnly.sol
Safes may want to be able to use multi-send for combining configuring calls such as `enableModule`, `setGuard` with each other or other external calls however specifying the safe's own address is impossible to currently do in initialization calls as the create2 salt for the safe depends on the hash of the `initializer` data which creates an unresolvable circular dependency. Allowing `address(0)` to act as an alias for "self" allows configuring calls to easily be specified at initialization which is useful for people who want to deploy safes that enable certain modules/guards from the start.
**Implementation Explanation**
The expression uses a binary-OR combined with a multiplication to implement a branch-less version of the following statement:
```solidity
to = to == address(0) ? …
```
> Add ability to implicitly specify "self" in multi-send

- contracts/Safe.sol
- contracts/handler/CompatibilityFallbackHandler.sol
- package.json
- test/core/Safe.Signatures.spec.ts
> Check Signatures moved to Safe.sol

- .github/workflows/certora.yml
This PR pins the Certora CLI version in CI. We started seeing unrelated failures because of, what appears to be, incompatibilities with the new version.
> Pin Certora CLI Version in CI

- benchmark/Safe.MultiSend.spec.ts
- benchmark/utils/setup.ts
- contracts/libraries/MultiSend.sol
- contracts/libraries/MultiSendCallOnly.sol
- contracts/test/DelegateCaller.sol
This PR closes #734 by directly using the `returndatasize()` instead of storing it in memory and retrieving it later. ~Accessing `returndatasize()` is always cheaper than `mstore` and multiple `mload`'s~.
On checking further, it was found that there are no differences in terms of gas usage for transactions (extra tests were added for `MultiSend` to verify), while 1 byte is saved during deployment (checked using `codesize`).
Note: Benchmark failing in this PR is expected: [Source](https://github.com/safe-global/safe-smart-account/pull/736#issuecomment-1934037016)
> Using `returndatasize()` in assembly.

- certora/applyHarness.patch
#751 accidentally left some testing code in the harness patch which broke CI - this PR attempts to fix things.
> Remove Leftover Testing Code In Harness Patch

- contracts/Safe.sol
- contracts/SafeL2.sol
- contracts/base/ModuleManager.sol
- test/l2/Safe.Execution.spec.ts
Fixes: #735 and #773
- Add a hook function `_onAfterExecTransactionFromModule` that gets called after execution from module.
- SafeL2 overrides this function to emit event `SafeModuleTransaction`.
- Add test that checks if `execTransactionFromModuleReturnData` in SafeL2 emits `SafeModuleTransaction` event.
```
Safe 21814 bytes (limit is 24576)
SafeL2 22632 bytes (limit is 24576)
```
```
Safe 21781 bytes (limit is 24576)
SafeL2 22623 bytes (limit is 24576)
```
Changes in this PR add additional overhead of `49` gas
```
·------------------------------------------------------------|----------------------------|-------------|------------------------------·
|                    Solc version: 0.7.6                     ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 100000000 gas  │ …
```
> Fix compilation issue with solidity versions >= 0.8.12

- contracts/Safe.sol
- contracts/SafeL2.sol
- contracts/base/ModuleManager.sol
- test/core/Safe.Execution.spec.ts
- test/l2/Safe.Execution.spec.ts
Fixes #775, #735
To have a broader context on overall changes in the code use this [diff](https://github.com/safe-global/safe-smart-account/compare/499b17ad..improvement-execTransaction-post-call-hook)
- Add a pre-hook function onBeforeExecTransaction
- Refactor changes in #772, #774
- Add a pre-hook function onBeforeExecTransactionFromModule
- Change function visibility of execTransaction from public to external
Increase by 51 bytes in Safe with diff: https://github.com/safe-global/safe-smart-account/compare/499b17ad..improvement-execTransaction-post-call-hook:
```
Safe 21832 bytes (limit is 24576)
SafeL2 22612 bytes (limit is 24576)
```
```
Safe 21781 bytes (limit is 24576)
SafeL2 22623 bytes (limit is 24576)
```
- Increase by 79 gas in execTransaction calls
- Increase by 44 gas in …
> Create a pre call hook onBeforeExecTransaction

- benchmark/utils/setup.ts
- test/accessors/SimulateTxAccessor.spec.ts
- test/core/Safe.Execution.spec.ts
- test/core/Safe.GuardManager.spec.ts
- test/core/Safe.Incoming.spec.ts
- test/core/Safe.ModuleManager.spec.ts
- test/core/Safe.OwnerManager.spec.ts
- test/core/Safe.Signatures.spec.ts
- test/core/Safe.StorageAccessible.spec.ts
- test/factory/ProxyFactory.spec.ts
- test/guards/DebugTransactionGuard.spec.ts
- test/guards/DelegateCallTransactionGuard.spec.ts
- test/guards/OnlyOwnersGuard.spec.ts
- test/guards/ReentrancyTransactionGuard.spec.ts
- test/handlers/CompatibilityFallbackHandler.spec.ts
- test/integration/Safe.0xExploit.spec.ts
- test/integration/Safe.ReservedAddresses.spec.ts
- test/l2/Safe.Execution.spec.ts
- test/libraries/CreateCall.spec.ts
- test/libraries/Migration.spec.ts
- test/libraries/MultiSend.spec.ts
- test/libraries/MultiSendCallOnly.spec.ts
- test/libraries/SafeToL2Setup.spec.ts
- test/libraries/SignMessageLib.spec.ts
- test/utils/setup.ts
Fixes #780 
This PR uses the typescript `types` to pass the parameters to `getSafeWithOwners(...)` as objects. All the parameters are kept as `readonly` because it is not supposed to change within the function (though `optional` parameters are assigned default values during restructuring).
Bonus Point: Found that `getSafeWithSingleton(...)` didn't use the `threshold` and `fallbackHandler` parameters in the current codebase, thus removing them for now (please comment if it should be reverted).
> `getSafeWithOwners` using types

- benchmark/utils/setup.ts
- test/accessors/SimulateTxAccessor.spec.ts
- test/core/Safe.Execution.spec.ts
- test/core/Safe.GuardManager.spec.ts
- test/core/Safe.Incoming.spec.ts
- test/core/Safe.ModuleManager.spec.ts
- test/core/Safe.OwnerManager.spec.ts
- test/core/Safe.Signatures.spec.ts
- test/core/Safe.StorageAccessible.spec.ts
- test/factory/ProxyFactory.spec.ts
- test/guards/DebugTransactionGuard.spec.ts
- test/guards/DelegateCallTransactionGuard.spec.ts
- test/guards/OnlyOwnersGuard.spec.ts
- test/guards/ReentrancyTransactionGuard.spec.ts
- test/handlers/CompatibilityFallbackHandler.spec.ts
- test/integration/Safe.0xExploit.spec.ts
- test/integration/Safe.ReservedAddresses.spec.ts
- test/l2/Safe.Execution.spec.ts
- test/libraries/CreateCall.spec.ts
- test/libraries/Migration.spec.ts
- test/libraries/MultiSend.spec.ts
- test/libraries/MultiSendCallOnly.spec.ts
- test/libraries/SafeMigration.spec.ts
- test/libraries/SafeToL2Migration.spec.ts
- test/libraries/SafeToL2Setup.spec.ts
- test/libraries/SignMessageLib.spec.ts
- test/utils/setup.ts
Fixes #802 
This PR unifies `getSafeWithOwners(...)` and `getSafeWithSingleton(...)` by editing the `getSafeTemplate(...)` to use an inside function which also takes the `singleton` as a parameter.
> Unifying function to get Safe implementation

- .gitignore
- contracts/libraries/SafeMigration.sol
- contracts/libraries/SafeToL2Migration.sol
- contracts/libraries/SafeToL2Setup.sol
This PR makes the changes based on Certora's audit report for the Safe Migration Contracts. Changes are only made to the `SafeToL2Migration` contract. Most of the changes are related to reducing gas consumption, typos and comments.
> Audit Changes for `v1.4.1-2`

- contracts/libraries/SafeMigration.sol
This PR removes the `payable` casting based on the comment https://github.com/safe-global/safe-smart-account/pull/815#discussion_r1734636149
> Removing `payable`

- contracts/examples/guards/DebugTransactionGuard.sol
- contracts/libraries/SafeMigration.sol
- contracts/libraries/SafeToL2Migration.sol
- contracts/libraries/SafeToL2Setup.sol
This PR makes the changes based on Certora's audit report from the branch `release/v1.4.1-2` to `main`.
In the release branch, we used the `ISafe` contract written inside the respective library files, but with `main`, we use the `ISafe` standard interface in the `interfaces` folder. Similarly, `Enum` was moved from `common` to `libraries`, and thus that is used for the same in the migration contracts.
Note: A `fmt` change was made to `DebugTransactionGuard.sol`.
> Audit Changes for `v1.4.1-2` cherry picked from `release/v1.4.1-2`

- src/deploy/deploy_libraries.ts
This PR adds the `SafeToL2Setup` deployment (already added in the `main` with #816) to the release branch for `v1.4.1`.
> `SafeToL2Setup` deployment script

- .github/workflows/ci.yml
Previously we only checked coverage using `npm run coverage` which I believe only checked `hardhat test --network hardhat`, thus not checking the rest of the types of test based on L1, L2 and ZK. This adds another job in the CI which checks for the same.
> Tests job updated in Workflow

- contracts/Safe.sol
- test/core/Safe.Execution.spec.ts
- test/core/Safe.FallbackManager.spec.ts
- test/core/Safe.GuardManager.spec.ts
- test/core/Safe.ModuleManager.spec.ts
- test/core/Safe.OwnerManager.spec.ts
- test/guards/ReentrancyTransactionGuard.spec.ts
- test/libraries/CreateCall.spec.ts
- test/libraries/MultiSend.spec.ts
- test/libraries/MultiSendCallOnly.spec.ts
- test/libraries/SafeToL2Setup.spec.ts
Fixes #715
This PR implements error propagation for internal TX so the user/dev can know the reason for revert instead of generic `GS013`.
> Error propagation for internal TX

- contracts/interfaces/IModuleManager.sol
While working on an indexer for module events, I noticed this comment is no longer valid as `SafeL2` now uses `onBeforeExecTransactionFromModule` to emit the `SafeModuleTransaction` event.
> fix: remove invalid documentation on execTransactionFromModule

- contracts/proxies/SafeProxyFactory.sol
- test/factory/ProxyFactory.spec.ts
As part of improving the capabilities for indexing safe creation data, a new set of functions is introduced which emits an extra event named `ProxyCreationL2` which also emits the `initializer` and `saltNonce`. The previous function remains the same for backward compatibility.
> Emit Event for `initializer` and `saltNonce` data

- contracts/handler/ExtensibleFallbackHandler.sol
- contracts/handler/HandlerContext.sol
- contracts/handler/extensible/ERC165Handler.sol
- contracts/handler/extensible/ExtensibleBase.sol
- contracts/handler/extensible/FallbackHandler.sol
- contracts/handler/extensible/MarshalLib.sol
- contracts/handler/extensible/SignatureVerifierMuxer.sol
- contracts/handler/extensible/TokenCallbacks.sol
- contracts/test/TestMarshalLib.sol
- contracts/test/TestSafeSignatureVerifier.sol
- src/deploy/deploy_handlers.ts
- test/handlers/ExtensibleFallbackHandler.spec.ts
- test/handlers/HandlerContext.spec.ts
- test/utils/extensible.ts
- test/utils/setup.ts
This PR brings the `ExtensibleFallbackHandler` created [here](https://github.com/rndlabs/safe-contracts/blob/merged-efh-sigmuxer/contracts/handler/ExtensibleFallbackHandler.sol) to `safe-smart-account` repo. Changes taken based on [git diff](https://github.com/safe-global/safe-smart-account/compare/main...rndlabs:safe-contracts:main).
Some small changes were made like:
- Adapting tests to the `safe-smart-account` repo.
- Remove unused import.
- Replace global importing (based on our lint setup) with specific contracts required.
> Extensible Fallback Handler

- CHANGELOG.md
- contracts/Safe.sol
- docs/safe_tx_gas.md
This pull request includes updates to contract addresses in the `CHANGELOG.md`, a minor comment correction in `Safe.sol`, and a rephrasing in the `safe_tx_gas.md` documentation.
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL58-R91): Updated various contract addresses for `Safe`, `SafeL2`, `SafeProxyFactory`, `TokenCallbackHandler`, `CompatibilityFallbackHandler`, `ExtensibleFallbackHandler`, `MultiSend`, `MultiSendCallOnly`, `SignMessageLib`, `SafeToL2Migration`, `SafeMigration`, and `SimulateTxAccessor` for both EVM and ZKSync.
* [`contracts/Safe.sol`](diffhunk://#diff-587b494ea631bb6b7adf4fc3e1a2e6a277a385ff16e1163b26e39de24e9483deL303-R303): Corrected a comment to fix a typo from "signatures bytes" to "signature bytes".
* …
> New addresses and small typo rectified

- contracts/Safe.sol
- contracts/base/ModuleManager.sol
- contracts/handler/extensible/MarshalLib.sol
- contracts/handler/extensible/SignatureVerifierMuxer.sol
- contracts/libraries/MultiSend.sol
- contracts/libraries/MultiSendCallOnly.sol
- contracts/proxies/SafeProxy.sol
- contracts/test/DelegateCaller.sol
- docs/safe_tx_gas.md
This PR does a once-over on memory Safety for the 1.5.0 contracts. In particular, there were a couple of missing `memory-safe` tags for some assembly blocks which were preventing the IR assembler from working correctly.
Additionally, since the `MultiSend*` contracts changed anyway in 1.5.0, I took this opportunity to change the assembly to be memory-safe so that we can tag it. Note that it only adds more code in the revert case, so it should not have a negative impact for most use-cases.
Furthermore, I added a comment explaining why we did not make the `SafeProxy` contract memory-safe (that is one intentional).
Lastly, I noticed that there were some `eq(..., 0)` assembly calls which can be written as `iszero(...)` to save some gas and code. Again, it was an opportunistic change as the …
> Assembly Memory Safety

- package.json
This pull request includes a small but significant change to the `package.json` file to enhance the testing process.
Enhancements to testing:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22-R22): Modified the `test` script to include running `test:zk` to ensure zkSync tests are executed along with other tests.
> enable zksync tests again

- certora/specs/NativeTokenRefund.spec
- certora/specs/Safe.spec
- certora/specs/Signatures.spec
- contracts/Safe.sol
- contracts/handler/CompatibilityFallbackHandler.sol
- contracts/handler/extensible/ERC165Handler.sol
- contracts/handler/extensible/ExtensibleBase.sol
- contracts/handler/extensible/FallbackHandler.sol
- contracts/handler/extensible/SignatureVerifierMuxer.sol
- contracts/interfaces/ISafe.sol
- contracts/test/TestSafeSignatureVerifier.sol
- test/core/Safe.Signatures.spec.ts
- test/handlers/CompatibilityFallbackHandler.spec.ts
- test/handlers/ExtensibleFallbackHandler.spec.ts
This commit disables support for pre-approved signatures from `msg.sender` for `isValidSignature` calls.
Note that we remove the new 1.5.0-only `checkSignatures` interface in favour of one with `executor` explicitly provided to avoid issues for contracts that make use of this function.
> Disable Pre-approved IsValidSignature

- .github/ISSUE_TEMPLATE/bug_report.md
- docs/safe_tx_gas.md
Corrected `considely` to `concisely`
Corrected `hhttps` to `https`
> fix: typos in documentation files

- certora/specs/NativeTokenRefund.spec
- tests_deprecated/utils/execution.js
This PR focuses on correcting typos and improving clarity in comments.
Thank you very much.
> fix: typos in comments

- contracts/base/OwnerManager.sol
This pull request includes a change which allows 1 SLOAD to be saved by emitting an existing memory variable instead of reading from storage.
* [`contracts/base/OwnerManager.sol`](diffhunk://#diff-795fb06764b4c2d991707584a31509badf0b036c9401bfbcb82d6bc9fdebab82L113-R113): Modified the `emit` statement in the `setThreshold` function to use the `_threshold` parameter instead of `threshold`, ensuring the value from memory is emitted.
> [Certora Audit] G-02. `OwnerManager.changeThreshold()` event update

- contracts/common/SecuredTokenTransfer.sol
- contracts/proxies/SafeProxy.sol
This pull request includes updates to comments in the Solidity smart contracts to clarify the usage of the `keccak256` function. The changes ensure that the comments accurately reflect the encoding process used in the contracts.
Changes to comments for clarity:
* [`contracts/common/SecuredTokenTransfer.sol`](diffhunk://#diff-7a34930a339acfe3b45e163bee3e08df2132c01826e6e03771827a4181c6f567L19-R19): Updated the comment to specify that `0xa9059cbb` is the `bytes4` encoding of `keccak256("transfer(address,uint256)")`.
* [`contracts/proxies/SafeProxy.sol`](diffhunk://#diff-754f853ea53666aa85b2d27bbcc0623b7cfd83449e0b949eed39dde8f01ba1cdL41-R41): Updated the comment to specify that `0xa619486e` is the `bytes4` encoding of `keccak256("masterCopy()")`.
> [Certora Audit] I-02. Some comments say `keccak` instead of `keccak256`

- contracts/base/OwnerManager.sol
This pull request includes a small but important change to the `removeOwner` function in the `OwnerManager` contract. The change optimizes the decrement operation for the `ownerCount` variable.
The previous code reads from storage twice with the `ownerCount` variable. By doing pre-decrement (which is cheaper than post-decrement), we can save on 1 SLOAD.
Optimization:
* [`contracts/base/OwnerManager.sol`](diffhunk://#diff-795fb06764b4c2d991707584a31509badf0b036c9401bfbcb82d6bc9fdebab82L74-L80): Modified the `removeOwner` function to use pre-decrement for `ownerCount` to improve efficiency and ensure the threshold check is performed correctly.
> [Certora Audit] G-01. `OwnerManager.removeOwner()`: 1 SLOAD can be saved in the normal path

- contracts/handler/extensible/ERC165Handler.sol
This pull request includes an important update to the `ERC165Handler` contract to improve the handling of interface support and streamline the code. The most significant changes are as follows:
* [`contracts/handler/extensible/ERC165Handler.sol`](diffhunk://#diff-aa0838f20fd3f37b00dc661645b4641500e68762b9b624addb99465fcc65a3e0L38-R48): Refactored the logic for checking and updating the support status of interfaces by introducing a local `mapping` reference. This change simplifies the code and ensures that the interface support status is updated correctly.
> [Certora Audit] G-03. `ERC165Handler.setSupportedInterface()`: Logic and storage access optimization

- contracts/handler/extensible/ExtensibleBase.sol
This pull request includes a refactor to the `_setSafeMethod` function in the `ExtensibleBase` contract to improve memory access.
The following optimizes the logic and minimizes storage accesses:
* [`contracts/handler/extensible/ExtensibleBase.sol`](diffhunk://#diff-e395e05c7e2951461c2e599137367a6a3304e849f3c522903d74f1a50f23b577L49-R57): Modified the `_setSafeMethod` function to use a local variable `safeMethod` for accessing the `safeMethods` mapping, which simplifies and clarifies the code.
> [Certora Audit] G-04. `ExtensibleBase._setSafeMethod()`: storage access optimization

- contracts/proxies/SafeProxyFactory.sol
This pull request includes a critical update to the `SafeProxyFactory` contract in the `contracts/proxies/SafeProxyFactory.sol` file. The change improves the gas cost of the assembly code by replacing the `eq` function with the `iszero` function.
Key change:
* [`contracts/proxies/SafeProxyFactory.sol`](diffhunk://#diff-53aac98a01e16743466b00bdcb233208f95e1113cc90b95181187d9862b4ad6eL43-R43): Replaced the `eq` function with the `iszero` function in the assembly block to improve code readability and reliability.
> [Certora Audit] G-05. Use `iszero` instead of `eq(*, 0)`

- contracts/handler/ExtensibleFallbackHandler.sol
This pull request includes a change to the `ExtensibleFallbackHandler` contract in the `contracts/handler/ExtensibleFallbackHandler.sol` file. The change modifies the `_supportsInterface` function to reorder the interface checks for `ERC721TokenReceiver`, `ERC1155TokenReceiver`, and `IFallbackHandler`. This helps in taking advantage of the short-circuit evaluation.
Changes to interface support order:
* [`contracts/handler/ExtensibleFallbackHandler.sol`](diffhunk://#diff-aa345618c4d3f173b09e211d0bd0eec0747177aab345bf8b9f5bbc874a765fe3R21-R26): Reordered the interface checks in the `_supportsInterface` function to place `ERC721TokenReceiver` and `ERC1155TokenReceiver` before `IFallbackHandler`.
> [Certora Audit] G-06. `ExtensibleFallbackHandler._supportsInterface()`: save gas via short-circuit evaluation

- contracts/Safe.sol
- contracts/base/ModuleManager.sol
- contracts/base/OwnerManager.sol
- contracts/common/StorageAccessible.sol
- contracts/handler/extensible/ERC165Handler.sol
- contracts/libraries/SafeToL2Migration.sol
This pull request includes several changes to increment and decrement operations in various Solidity contract files. The primary goal is to decrease gas usage.
Pre-increments and pre-decrements are cheaper.
For a uint256 i variable, the following is true with the Optimizer enabled at 10k:
Increment:
- i += 1 is the most expensive form
- i++ costs 6 gas less than i += 1
- ++i costs 5 gas less than i++ (11 gas less than i += 1)
Decrement:
- i -= 1 is the most expensive form
- i-- costs 11 gas less than i -= 1
- --i costs 5 gas less than i-- (16 gas less than i -= 1)
Changes to increment and decrement operations:
* [`contracts/Safe.sol`](diffhunk://#diff-587b494ea631bb6b7adf4fc3e1a2e6a277a385ff16e1163b26e39de24e9483deL296-R296): Updated the for loop to use the prefix increment operator in …
> [Certora Audit] G-10. ++i costs less gas compared to i++ or i+=1

- contracts/handler/extensible/MarshalLib.sol
- contracts/handler/extensible/SignatureVerifierMuxer.sol
This pull request includes changes to the `contracts/handler/extensible` directory, specifically in the `MarshalLib.sol` and `SignatureVerifierMuxer.sol` files. The changes focus on improving the handling of data and selectors within assembly code blocks to decrease gas usage.
Improvements to data handling and selector extraction:
* [`contracts/handler/extensible/MarshalLib.sol`](diffhunk://#diff-7122c44132b6fc89cd7c9f3c48519c88aaf7308705a1170d307d72465eb9e1c9L41-R41): Modified the way the `handler` is extracted from `data` by using a bitwise AND operation to ensure proper extraction of the handler address. [[1]](diffhunk://#diff-7122c44132b6fc89cd7c9f3c48519c88aaf7308705a1170d307d72465eb9e1c9L41-R41) [[2]](diffhunk://#diff-7122c44132b6fc89cd7c9f3c48519c88aaf7308705a1170d307d72465eb9e1c9L5 …
> [Certora Audit] G07. Use a mask instead of shifting left and right

- contracts/Safe.sol
- contracts/common/StorageAccessible.sol
This pull request includes optimizations to the gas usage in the `Safe.sol` and `StorageAccessible.sol` contracts by replacing multiplication operations with bitwise shift operations. While the `DIV / MUL` opcode uses 5 gas, the `SHR / SHL` opcode only uses 3 gas.
Gas optimization changes:
* [`contracts/Safe.sol`](diffhunk://#diff-587b494ea631bb6b7adf4fc3e1a2e6a277a385ff16e1163b26e39de24e9483deL168-R169): Replaced the multiplication operation `* 64` with the bitwise shift operation `<< 6` to reduce gas costs in the `gasleft` check.
* [`contracts/common/StorageAccessible.sol`](diffhunk://#diff-a7dd65d90b0567bb9ba14ecd4ff414529a934cd3752ccf309800fad93fba354eL18-R18): Replaced the multiplication operation `* 32` with the bitwise shift operation `<< 5` to reduce gas costs when creating a new …
> [Certora Audit] G-08. Use shift right/left instead of division/multiplication if possible

- certora/applyHarness.patch
- certora/conf/execute.conf
- certora/conf/extensible.conf
- certora/conf/fallback.conf
- certora/conf/guards.conf
- certora/conf/hash.conf
- certora/conf/run.conf
- certora/conf/setup.conf
- certora/harnesses/ExtensibleFallbackHandlerHarness.sol
- certora/harnesses/SafeHarness.sol
- certora/mocks/DummyHandler.sol
- certora/mocks/ModuleGuardMock.sol
- certora/mocks/ModuleGuardMockDuplicate.sol
- certora/mocks/TxnGuardMock.sol
- certora/mocks/TxnGuardMockDuplicate.sol
- certora/specs/Execute.spec
- certora/specs/Extensible.spec
- certora/specs/Fallback.spec
- certora/specs/Guards.spec
- certora/specs/Hash.spec
- certora/specs/Safe.spec
- certora/specs/Setup.spec
This pull request corresponds to the formal verification aspect of the Safe v1.5 audit done by Certora.
Configuration and Specification files corresponding to new rules:
* `execute.conf` and `Execute.spec`
* `extensible.conf` and `Extensible.spec`
* `fallback.conf` and `Fallback.spec`
* `guards.conf` and `Guards.spec`
* `hash.conf` and `Hash.spec`
* `setup.conf` and `Setup.spec`
Harness:
* `ExtensibleFallbackHandlerHarness.sol` to reason about the fallback handler
Mocks:
* `DummyHandler.sol` for reasoning about the fallback handler
* `TxnGuardMock.sol` and `TxnGuardMockDuplicate.sol` for reasoning about the transaction guard
* `ModuleGuardMock.sol` and `ModuleGuardMockDuplicate.sol` for reasoning about the module guard
* `applyHarness.patch` - added some minor munging as explained in the …
> Formal Verification for Safe v1.5 Audit

- certora/specs/OwnerReach.spec
Hello, I found a typo error in `certora/specs/OwnerReach.spec`: 
`isOwnerNotSelfOrSentinal ` -> `isOwnerNotSelfOrSentinel`
Thank you.
> chore: fix typo in certora/specs/OwnerReach.spec
