safe-global/safe-smart-account

contracts/GnosisSafe.sol
=> Make approvedHashes and signedMessage public

package.json, test/utils/general.js
those are the files/folders installed when  used as a dependency
=> missing build folder for npm-package files folder

contracts/GnosisSafe.sol, contracts/proxies/ProxyFactory.sol, test/gnosisSafeDeploymentViaCreate2.js
=> Add method to calculate new proxy create2 address

contracts/GnosisSafe.sol, contracts/interfaces/ISignatureValidator.sol, test/gnosisSafe0xExploit.js, test/utils/execution.js
Closes #112 
- Use static call for EIP-1271 check
- Add test for 0x exploit
=> Closes #112: Use static call for EIP-1271 check

README.md, contracts/GnosisSafe.sol, contracts/libraries/MultiSend.sol, test/multiSend.js, test/utils/general.js, truffle.js
- Use packed encoding for multisend transactions data
=> Refactor MultiSend

contracts/GnosisSafe.sol, contracts/base/Executor.sol, contracts/common/Enum.sol, contracts/common/SecuredTokenTransfer.sol, contracts/common/SignatureDecoder.sol, contracts/libraries/CreateCall.sol, contracts/libraries/MultiSend.sol, test/createCall.js, test/gnosisSafeSignatureTypes.js, test/gnosisSafeTransactionExecution.js, test/stateChannelModule.js
- Extract create support from Safe contract to lib
- Add create2 support
=> Move create and create2 support to lib

contracts/proxies/ProxyFactory.sol, test/gnosisSafeDeploymentViaCreate2.js
- Write test for it
- Remove ';' on the test file
- Closes #121
=> Throw error if create2 returns 0 address

contracts/common/MasterCopy.sol, test/gnosisSafeManagement.js
- Add test for Safe master copy change
- Remove spaces and ;
- Closes #123
=> Emit event when master copy changes

package-lock.json, package.json, scripts/downgrade_safe.js, test/createAndAddModules.js, test/gnosisSafeManagement.js, test/gnosisSafeTransactionExecution.js, test/multiSend.js, test/utils/execution.js
- Adds a test in createAndAddModules where an existing Safe is used
- Closes #125: Use different owners in ETH payment test, to avoid weird behaviour
- Upgrade Solc to 0.5.11
=> Add test for creation and adding a module to existing Safe

contracts/base/ModuleManager.sol, contracts/common/SecuredTokenTransfer.sol, contracts/proxies/DelegateConstructorProxy.sol, contracts/proxies/PayingProxy.sol, test/gnosisSafeExecuteFromModule.js
This would allow modules to actively check what is returned when a module performs a call. For example this allows to make sure that a token transfer was successful.
=> Add method that returns data to modules

contracts/GnosisSafe.sol
- Improve readability 
- Improve gas usage
=> Inline functions

contracts/proxies/IProxyCreationCallback.sol, contracts/proxies/ProxyFactory.sol, test/gnosisSafeExecuteFromModule.js, test/proxyFactoryCallback.js
=> Allow to trigger callback after proxy creation (#141)

contracts/proxies/ProxyFactory.sol
This line was using a mix of tabs and spaces, fixed to only use spaces like the rest of the file.
=> Fixes mixed indentation style.

.gitignore, .vscode/launch.json, package.json
- Support debug in visual studio code
- Support specifying a test file with `npm test`, like `npm test test/createCall.js`
=> Support debug in visual studio code

README.md
Closes #173
- Update how to run all tests
- Added how to run a ganache-cli instance for Safe tests
=> Closes #173: Adjust docs how to run all tests

README.md
Closes #184 
* Mention that node 10 is required
=> Closes #184: Add node version requirement

contracts/base/ModuleManager.sol, test/gnosisSafeManagement.js
Closes #181: Add isModuleEnabled function
- Returns true if module is enabled and is not the sentinel address
=> Closes #181: Add isModuleEnabled function

contracts/GnosisSafe.sol, contracts/external/GnosisSafeMath.sol, test/safeTxGasEstimation.js, truffle-config.js
- Correctly check gas requirements
- Correctly set Solidity compiler settings
=> Fix audit comments

.openzeppelin/xdai.json, scripts/merge_oz.js, truffle.js
* Added contracts on xDai network
=> Deploy on xdai

.github/workflows/ci.yml, .travis.yml
Take a look on https://github.com/gnosis/safe-contracts/actions
=> Configure github actions

benchmark/GnosisSafe.ERC1155.spec.ts, benchmark/GnosisSafe.ERC20.spec.ts, benchmark/GnosisSafe.Ether.spec.ts, benchmark/GnosisSafe.Proxy.spec.ts, benchmark/utils/setup.ts, contracts/GnosisSafe.sol, contracts/base/GuardManager.sol, contracts/guards/DelegateCallTransactionGuard.sol, test/core/GnosisSafe.GuardManager.spec.ts, test/guards/DelegateCallTransactionGuard.spec.ts
Closes #224: Added transcation guard
- If set the calldata + msg.sender are send to the guard for further validation.
=> Closes #224: transaction guard

contracts/GnosisSafe.sol, docs/error_codes.md, test/core/GnosisSafe.Execution.spec.ts, test/core/GnosisSafe.ModuleManager.spec.ts, test/core/GnosisSafe.OwnerManager.spec.ts, test/libraries/CreateCall.spec.ts, test/libraries/MultiSend.spec.ts, test/utils/execution.ts, test/utils/multisend.ts
Closes #274 
Revert on failure if `safeTxGas == 0` and `gasPrice == 0`
Notes:
- If `safeTxGas` is set to 1 you get the previous behaviour
=> Closes #274: Revert on failure with safeTxGas 0

contracts/common/StorageAccessible.sol, contracts/handler/CompatibilityFallbackHandler.sol, contracts/interfaces/ViewStorageAccessible.sol, test/accessors/SimulateTxAccessor.spec.ts, test/core/GnosisSafe.StorageAccessible.spec.ts, test/handlers/CompatibilityFallbackHandler.spec.ts
- `simulateDelegatecallInternal` -> `simulateAndRevert`
- `simulateDelegatecall` -> `simulate`
=> Update StorageAccessible related function names

contracts/base/FallbackManager.sol, contracts/base/GuardManager.sol, contracts/proxies/GnosisSafeProxyFactory.sol, test/core/GnosisSafe.FallbackManager.spec.ts, test/core/GnosisSafe.GuardManager.spec.ts, test/factory/ProxyFactory.spec.ts
=> Add missing events

README.md, package.json, test/core/GnosisSafe.Execution.spec.ts, yarn.lock
- Test gas values had to be updated because of Berlin gas cost changes
=> Final repo adjustments before release

CHANGELOG.md
- The address was missing a `2` at the end
=> Update GnosisSafe address

hardhat.config.ts
- Ropsten
- Polygon Mumbai
- Polygon Mainnet
=> Add more Infura supported networks to deploy configuration

README.md
=> Added latest version notes to the readme

docs/safe_tx_gas.md
=> Closes #282

.github/workflows/ci.yml, .github/workflows/cla.yml
- Setup CLA workflow
- Run CI for PRs
=> Enable external contributions

contracts/base/GuardManager.sol
This PR updates the title in GuardManager.sol
=> Fix title in Guard Manager

docs/guidelines.md, docs/safe_tx_gas.md
=> Fix: typos

.prettierrc, contracts/common/Enum.sol, contracts/common/EtherPaymentFallback.sol, contracts/common/SecuredTokenTransfer.sol, contracts/common/SelfAuthorized.sol, contracts/common/SignatureDecoder.sol, contracts/common/Singleton.sol, contracts/common/StorageAccessible.sol
=> Docs: Improve documentation of `common/` contracts 

README.md
I have read the CLA Document and I hereby sign the CLA
Status icons show "unknown", because branch development does not exist.
showing "main" branch for those icons now.
=> Update README.md - fixed icons

test/libraries/MultiSendCallOnly.spec.ts
This is a correction of my last PR
=> Remove unused imports

.github/workflows/certora.yml, certora/harnesses/SafeHarness.sol, certora/scripts/verifySafe.sh, certora/specs/Safe.spec
Changes in PR:
- Add getter functions to get size of owners array
- Fix failing certora workflow (use `certora-cli` package instead of `certora-cli-beta`)
- Add invariant `safeOwnerCountConsistency`
=> Check owners list consistency

docs/overview.md
=> Change code block language identifier

CHANGELOG.md
This PR:
- Adds changelog for the version 1.5.0
=> Add 1.5.0 changelog

README.md
in package update of safe-singleton-factory to fix #664
=> Update README.md to add missing --save-dev

contracts/proxies/SafeProxyFactory.sol, docs/signatures.md
=> chore: fix typos

README.md
It is now ~~1.4.1-2~~ 1.4.1-3 with the migration contracts.
=> Update Documented Latest Release

.github/workflows/certora.yml, certora/requirements.txt
This PR adds the FV rules introduced in #901 to the workflow.
=> Certora Workfile Updated
